// This file contains the data structure for Adhigarams and sample Kurals
// You'll need to complete this with all 1330 Kurals

const adhigarams = [
  // Arathupal (Virtue) - Chapters 1-38
  { number: 1, nameTamil: "கடவுள் வாழ்த்து", nameEnglish: "Praise of God", paal: "Arathupal" },
  { number: 2, nameTamil: "வான்சிறப்பு", nameEnglish: "Excellence of Rain", paal: "Arathupal" },
  { number: 3, nameTamil: "நீத்தார் பெருமை", nameEnglish: "Greatness of Ascetics", paal: "Arathupal" },
  { number: 4, nameTamil: "அறன்வலியுறுத்தல்", nameEnglish: "Assertion of Virtue", paal: "Arathupal" },
  { number: 5, nameTamil: "இல்வாழ்க்கை", nameEnglish: "Domestic Life", paal: "Arathupal" },
  { number: 6, nameTamil: "வாழ்க்கைத் துணைநலம்", nameEnglish: "Excellence of Spouse", paal: "Arathupal" },
  { number: 7, nameTamil: "மக்கட்பேறு", nameEnglish: "Blessing of Children", paal: "Arathupal" },
  { number: 8, nameTamil: "அன்புடைமை", nameEnglish: "Possession of Love", paal: "Arathupal" },
  { number: 9, nameTamil: "விருந்தோம்பல்", nameEnglish: "Hospitality", paal: "Arathupal" },
  { number: 10, nameTamil: "இனியவைகூறல்", nameEnglish: "Speaking Pleasant Words", paal: "Arathupal" },
  { number: 11, nameTamil: "செய்ந்நன்றியறிதல்", nameEnglish: "Gratitude", paal: "Arathupal" },
  { number: 12, nameTamil: "நடுவு நிலைமை", nameEnglish: "Impartiality", paal: "Arathupal" },
  { number: 13, nameTamil: "அடக்கமுடைமை", nameEnglish: "Self-Control", paal: "Arathupal" },
  { number: 14, nameTamil: "ஒழுக்கமுடைமை", nameEnglish: "Good Conduct", paal: "Arathupal" },
  { number: 15, nameTamil: "பிறனில் விழையாமை", nameEnglish: "Not Coveting Another's Wife", paal: "Arathupal" },
  { number: 16, nameTamil: "பொறையுடைமை", nameEnglish: "Forbearance", paal: "Arathupal" },
  { number: 17, nameTamil: "அழுக்காறாமை", nameEnglish: "Not Envying", paal: "Arathupal" },
  { number: 18, nameTamil: "வெஃகாமை", nameEnglish: "Not Coveting", paal: "Arathupal" },
  { number: 19, nameTamil: "புறங்கூறாமை", nameEnglish: "Not Backbiting", paal: "Arathupal" },
  { number: 20, nameTamil: "பயனில சொல்லாமை", nameEnglish: "Not Speaking Profitless Words", paal: "Arathupal" },
  { number: 21, nameTamil: "தீவினையச்சம்", nameEnglish: "Dread of Evil Deeds", paal: "Arathupal" },
  { number: 22, nameTamil: "ஒப்புரவறிதல்", nameEnglish: "Duty to Society", paal: "Arathupal" },
  { number: 23, nameTamil: "ஈகை", nameEnglish: "Giving", paal: "Arathupal" },
  { number: 24, nameTamil: "புகழ்", nameEnglish: "Fame", paal: "Arathupal" },
  { number: 25, nameTamil: "அருளுடைமை", nameEnglish: "Compassion", paal: "Arathupal" },
  { number: 26, nameTamil: "புலான்மறுத்தல்", nameEnglish: "Abstinence from Meat", paal: "Arathupal" },
  { number: 27, nameTamil: "தவம்", nameEnglish: "Penance", paal: "Arathupal" },
  { number: 28, nameTamil: "கூடா ஒழுக்கம்", nameEnglish: "Inconsistent Conduct", paal: "Arathupal" },
  { number: 29, nameTamil: "கள்ளாமை", nameEnglish: "Not Stealing", paal: "Arathupal" },
  { number: 30, nameTamil: "வாய்மை", nameEnglish: "Truthfulness", paal: "Arathupal" },
  { number: 31, nameTamil: "வெகுளாமை", nameEnglish: "Not Being Angry", paal: "Arathupal" },
  { number: 32, nameTamil: "இன்னா செய்யாமை", nameEnglish: "Not Causing Harm", paal: "Arathupal" },
  { number: 33, nameTamil: "கொல்லாமை", nameEnglish: "Not Killing", paal: "Arathupal" },
  { number: 34, nameTamil: "நிலையாமை", nameEnglish: "Impermanence", paal: "Arathupal" },
  { number: 35, nameTamil: "துறவு", nameEnglish: "Renunciation", paal: "Arathupal" },
  { number: 36, nameTamil: "மெய்யுணர்தல்", nameEnglish: "Knowledge of Truth", paal: "Arathupal" },
  { number: 37, nameTamil: "அவாவறுத்தல்", nameEnglish: "Eradication of Desire", paal: "Arathupal" },
  { number: 38, nameTamil: "ஊழ்", nameEnglish: "Fate", paal: "Arathupal" },

  // Porutpal (Wealth/Polity) - Chapters 39-108
  { number: 39, nameTamil: "இறைமாட்சி", nameEnglish: "The Greatness of a King", paal: "Porutpal" },
  { number: 40, nameTamil: "கல்வி", nameEnglish: "Learning", paal: "Porutpal" },
  { number: 41, nameTamil: "கல்லாமை", nameEnglish: "Ignorance", paal: "Porutpal" },
  { number: 42, nameTamil: "கேள்வி", nameEnglish: "Listening", paal: "Porutpal" },
  { number: 43, nameTamil: "அறிவுடைமை", nameEnglish: "Knowledge", paal: "Porutpal" },
  { number: 44, nameTamil: "குற்றங்கடிதல்", nameEnglish: "Guarding Against Faults", paal: "Porutpal" },
  { number: 45, nameTamil: "பெரியாரைத் துணைக்கோடல்", nameEnglish: "Seeking the Aid of Great Men", paal: "Porutpal" },
  { number: 46, nameTamil: "சிற்றினஞ்சேராமை", nameEnglish: "Avoiding Mean Company", paal: "Porutpal" },
  { number: 47, nameTamil: "தெரிந்து செயல்வகை", nameEnglish: "Acting After Due Consideration", paal: "Porutpal" },
  { number: 48, nameTamil: "வலியறிதல்", nameEnglish: "Knowing Strength", paal: "Porutpal" },
  { number: 49, nameTamil: "காலமறிதல்", nameEnglish: "Knowing the Time", paal: "Porutpal" },
  { number: 50, nameTamil: "இடனறிதல்", nameEnglish: "Knowing the Place", paal: "Porutpal" },
  { number: 51, nameTamil: "தெரிந்துதெளிதல்", nameEnglish: "Selection and Confidence", paal: "Porutpal" },
  { number: 52, nameTamil: "தெரிந்துவினையாடல்", nameEnglish: "Acting After Deliberation", paal: "Porutpal" },
  { number: 53, nameTamil: "சுற்றந்தழால்", nameEnglish: "Cherishing Kinsmen", paal: "Porutpal" },
  { number: 54, nameTamil: "பொச்சாவாமை", nameEnglish: "Not Being Negligent", paal: "Porutpal" },
  { number: 55, nameTamil: "செங்கோன்மை", nameEnglish: "Ruling with Justice", paal: "Porutpal" },
  { number: 56, nameTamil: "கொடுங்கோன்மை", nameEnglish: "Cruel Governance", paal: "Porutpal" },
  { number: 57, nameTamil: "வெருவந்த செய்யாமை", nameEnglish: "Not Fearing", paal: "Porutpal" },
  { number: 58, nameTamil: "கண்ணோட்டம்", nameEnglish: "Benignity", paal: "Porutpal" },
  { number: 59, nameTamil: "ஒற்றாடல்", nameEnglish: "Espionage", paal: "Porutpal" },
  { number: 60, nameTamil: "ஊக்கமுடைமை", nameEnglish: "Energy", paal: "Porutpal" },
  { number: 61, nameTamil: "மடியின்மை", nameEnglish: "Lack of Laziness", paal: "Porutpal" },
  { number: 62, nameTamil: "ஆள்வினையுடைமை", nameEnglish: "Manly Effort", paal: "Porutpal" },
  { number: 63, nameTamil: "இடுக்கணழியாமை", nameEnglish: "Not Desponding in Trouble", paal: "Porutpal" },
  { number: 64, nameTamil: "அமைச்சு", nameEnglish: "The Office of Minister", paal: "Porutpal" },
  { number: 65, nameTamil: "சொல்வன்மை", nameEnglish: "Power of Speech", paal: "Porutpal" },
  { number: 66, nameTamil: "வினைத்தூய்மை", nameEnglish: "Purity in Action", paal: "Porutpal" },
  { number: 67, nameTamil: "வினைத்திட்பம்", nameEnglish: "Firmness in Action", paal: "Porutpal" },
  { number: 68, nameTamil: "வினைசெயல்வகை", nameEnglish: "Modes of Action", paal: "Porutpal" },
  { number: 69, nameTamil: "தூது", nameEnglish: "Embassy", paal: "Porutpal" },
  { number: 70, nameTamil: "மன்னரைச் சேர்ந்தொழுகல்", nameEnglish: "Conduct in the Presence of King", paal: "Porutpal" },
  { number: 71, nameTamil: "குறிப்பறிதல்", nameEnglish: "Reading the Mind", paal: "Porutpal" },
  { number: 72, nameTamil: "அவையறிதல்", nameEnglish: "Understanding the Council", paal: "Porutpal" },
  { number: 73, nameTamil: "அவையஞ்சாமை", nameEnglish: "Not Fearing the Council", paal: "Porutpal" },
  { number: 74, nameTamil: "நாடு", nameEnglish: "The Land", paal: "Porutpal" },
  { number: 75, nameTamil: "அரண்", nameEnglish: "The Fortress", paal: "Porutpal" },
  { number: 76, nameTamil: "பொருள்செயல்வகை", nameEnglish: "Means of Accumulating Wealth", paal: "Porutpal" },
  { number: 77, nameTamil: "படைமாட்சி", nameEnglish: "The Excellence of Army", paal: "Porutpal" },
  { number: 78, nameTamil: "படைச்செருக்கு", nameEnglish: "Military Strength", paal: "Porutpal" },
  { number: 79, nameTamil: "நட்பு", nameEnglish: "Friendship", paal: "Porutpal" },
  { number: 80, nameTamil: "நட்பாராய்தல்", nameEnglish: "Investigation of Friends", paal: "Porutpal" },
  { number: 81, nameTamil: "பழைமை", nameEnglish: "Old Friendship", paal: "Porutpal" },
  { number: 82, nameTamil: "தீநட்பு", nameEnglish: "Evil Friendship", paal: "Porutpal" },
  { number: 83, nameTamil: "கூடாநட்பு", nameEnglish: "Unreal Friendship", paal: "Porutpal" },
  { number: 84, nameTamil: "பேதைமை", nameEnglish: "Folly", paal: "Porutpal" },
  { number: 85, nameTamil: "புல்லறிவாண்மை", nameEnglish: "Ignorance", paal: "Porutpal" },
  { number: 86, nameTamil: "இகல்", nameEnglish: "Enmity", paal: "Porutpal" },
  { number: 87, nameTamil: "பகைமாட்சி", nameEnglish: "Greatness of Enemy", paal: "Porutpal" },
  { number: 88, nameTamil: "பகைத்திறந்தெரிதல்", nameEnglish: "Knowing the Quality of Enmity", paal: "Porutpal" },
  { number: 89, nameTamil: "உட்பகை", nameEnglish: "Internal Enmity", paal: "Porutpal" },
  { number: 90, nameTamil: "பெரியாரைப் பிழையாமை", nameEnglish: "Not Offending the Great", paal: "Porutpal" },
  { number: 91, nameTamil: "பெண்வழிச்சேறல்", nameEnglish: "Being Led by Women", paal: "Porutpal" },
  { number: 92, nameTamil: "வரைவின்மகளிர்", nameEnglish: "Wanton Women", paal: "Porutpal" },
  { number: 93, nameTamil: "கள்ளுண்ணாமை", nameEnglish: "Not Drinking Liquor", paal: "Porutpal" },
  { number: 94, nameTamil: "சூது", nameEnglish: "Gambling", paal: "Porutpal" },
  { number: 95, nameTamil: "மருந்து", nameEnglish: "Medicine", paal: "Porutpal" },
  { number: 96, nameTamil: "குடிமை", nameEnglish: "Nobility", paal: "Porutpal" },
  { number: 97, nameTamil: "மானம்", nameEnglish: "Honor", paal: "Porutpal" },
  { number: 98, nameTamil: "பெருமை", nameEnglish: "Greatness", paal: "Porutpal" },
  { number: 99, nameTamil: "சான்றாண்மை", nameEnglish: "Perfectness", paal: "Porutpal" },
  { number: 100, nameTamil: "பண்புடைமை", nameEnglish: "Courtesy", paal: "Porutpal" },
  { number: 101, nameTamil: "நன்றியில்செல்வம்", nameEnglish: "Wealth Without Gratitude", paal: "Porutpal" },
  { number: 102, nameTamil: "நாணுடைமை", nameEnglish: "Sense of Shame", paal: "Porutpal" },
  { number: 103, nameTamil: "குடிசெயல்வகை", nameEnglish: "Maintaining Family Tradition", paal: "Porutpal" },
  { number: 104, nameTamil: "உழவு", nameEnglish: "Agriculture", paal: "Porutpal" },
  { number: 105, nameTamil: "நல்குரவு", nameEnglish: "Poverty", paal: "Porutpal" },
  { number: 106, nameTamil: "இரவு", nameEnglish: "Begging", paal: "Porutpal" },
  { number: 107, nameTamil: "இரவச்சம்", nameEnglish: "Dread of Begging", paal: "Porutpal" },
  { number: 108, nameTamil: "கயமை", nameEnglish: "Baseness", paal: "Porutpal" },

  // Kamathupal (Love) - Chapters 109-133
  { number: 109, nameTamil: "தகையணங்குறுத்தல்", nameEnglish: "Praising Her Beauty", paal: "Kamathupal" },
  { number: 110, nameTamil: "குறிப்பறிவுறுத்தல்", nameEnglish: "Recognizing the Signs", paal: "Kamathupal" },
  { number: 111, nameTamil: "புணர்ச்சிவிதும்பல்", nameEnglish: "Rejoicing in Union", paal: "Kamathupal" },
  { number: 112, nameTamil: "நலம்புனைந்துரைத்தல்", nameEnglish: "Praise of Her Beauty", paal: "Kamathupal" },
  { number: 113, nameTamil: "காதற்சிறப்புரைத்தல்", nameEnglish: "Describing the Excellence of Love", paal: "Kamathupal" },
  { number: 114, nameTamil: "நாணுத்துறவுரைத்தல்", nameEnglish: "Abandoning Shyness", paal: "Kamathupal" },
  { number: 115, nameTamil: "அலரறிவுறுத்தல்", nameEnglish: "Awareness of Rumor", paal: "Kamathupal" },
  { number: 116, nameTamil: "பிரிவாற்றாமை", nameEnglish: "Inability to Bear Separation", paal: "Kamathupal" },
  { number: 117, nameTamil: "படர்மெலிந்திரங்கல்", nameEnglish: "Pining in Pallor", paal: "Kamathupal" },
  { number: 118, nameTamil: "கண்விதுப்பழிதல்", nameEnglish: "Blaming the Eyes", paal: "Kamathupal" },
  { number: 119, nameTamil: "பசப்புறுபருவரல்", nameEnglish: "Pallor of Separation", paal: "Kamathupal" },
  { number: 120, nameTamil: "தனிப்படர்மிகுதி", nameEnglish: "Excessiveness of Solitary Suffering", paal: "Kamathupal" },
  { number: 121, nameTamil: "நினைந்தவர்புலம்பல்", nameEnglish: "Lament of Thought", paal: "Kamathupal" },
  { number: 122, nameTamil: "கனவுநிலையுரைத்தல்", nameEnglish: "Describing the Dream State", paal: "Kamathupal" },
  { number: 123, nameTamil: "பொழுதுகண்டிரங்கல்", nameEnglish: "Lamenting at Different Times", paal: "Kamathupal" },
  { number: 124, nameTamil: "உறுப்புநலனழிதல்", nameEnglish: "Loss of Bodily Beauty", paal: "Kamathupal" },
  { number: 125, nameTamil: "நெஞ்சொடுகிளத்தல்", nameEnglish: "Addressing the Heart", paal: "Kamathupal" },
  { number: 126, nameTamil: "நிறையழிதல்", nameEnglish: "Loss of Modesty", paal: "Kamathupal" },
  { number: 127, nameTamil: "அவர்வயின்விதும்பல்", nameEnglish: "Rejoicing in Him", paal: "Kamathupal" },
  { number: 128, nameTamil: "குறிப்பறிவுறுத்தல்", nameEnglish: "Sending the Messenger", paal: "Kamathupal" },
  { number: 129, nameTamil: "புணர்ச்சிவிதும்பல்", nameEnglish: "Lamenting the Infidelity", paal: "Kamathupal" },
  { number: 130, nameTamil: "நெஞ்சொடுபுலத்தல்", nameEnglish: "Complaining to the Heart", paal: "Kamathupal" },
  { number: 131, nameTamil: "புலவி", nameEnglish: "Feigned Anger", paal: "Kamathupal" },
  { number: 132, nameTamil: "புலவிநுணுக்கம்", nameEnglish: "Subtlety of Feigned Anger", paal: "Kamathupal" },
  { number: 133, nameTamil: "ஊடலுவகை", nameEnglish: "The Pleasure of Sulking", paal: "Kamathupal" },
];

module.exports = { adhigarams, kurals };
